// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

console.log('[Supabase] URL:', SUPABASE_URL);
console.log('[Supabase] Anon Key:', SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.slice(0, 6) + '...' : 'undefined');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a fallback client if environment variables are missing
export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  : createClient<Database>('https://placeholder.supabase.co', 'placeholder-key');